#ifndef ADAPTER_H
#define ADAPTER_H

typedef enum adapter_state_e {
    STATE_NONE,
    STATE_INIT,
    STATE_IDENTIFYING,
    STATE_AUTHENTICATING,
    STATE_RUNNING,
    STATE_POWER_OFF,
} adapter_state_t;

#define ANNOUNCE_INTERVAL_MS 2000
#define VELOCITY_THRESH 10
#define TRIGGER_HOLD_MS 40
#define ON_DELAY_MS 20

#define ENDPOINT_DIR_OUT 0x00
#define ENDPOINT_DIR_IN 0x80

#define ADAPTER_OUT_INTERVAL 4
#define ADAPTER_IN_INTERVAL 4

#endif  // ADAPTER_H